export enum DEFAULT_ROLE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN_STAFF = 'ADMIN_STAFF',
  ORGANIZATION_ADMIN = 'ORGANIZATION_ADMIN',
  ORGANIZATION_MEMBER = 'ORGANIZATION_MEMBER',
  MANAGER = 'MANAGER',
  SUPERINTENDENT = 'SUPERINTENDENT',
  SUPERVISOR = 'SUPERVISOR',
  CREW_MEMBER = 'CREW_MEMBER',
}

export enum DEFAULT_ROLE_NAME {
  SUPER_ADMIN = 'Super Admin',
  ADMIN_STAFF = 'Admin Staff',
  ORGANIZATION_ADMIN = 'Organization Admin',
  ORGANIZATION_MEMBER = 'Organization member',
  MANAGER = 'Manager',
  SUPERINTENDENT = 'Superintendent',
  SUPERVISOR = 'Supervisor',
  CREW_MEMBER = 'Crew Member',
}
