export enum MODULE_CODE {
  // Main Menu (start)
  HOMEPAGE = 'HOMEPAGE',
  ORGANIZATION_MANAGEMENT = 'ORGANIZATION_MANAGEMENT',
  SYSTEM_CONFIGURATION = 'SYSTEM_CONFIGURATION',
  SYSTEM_CONFIGURATION_USER = 'SYSTEM_CONFIGURATION_USER',
  CUSTOMER_SUPPORT = 'CUSTOMER_SUPPORT',

  MASTER_RESOURCES_ADMIN = 'MASTER_RESOURCES_ADMIN',
  MASTER_RESOURCES = 'MASTER_RESOURCES',

  // Main Menu (end)

  DASHBOARD = 'DASHBOARD',
  DASHBOARD_ADMIN = 'DASHBOARD_ADMIN',
  REGISTRATIONS = 'REGISTRATIONS',
  ORGANIZATIONS = 'ORGANIZATIONS',
  ORGANIZATION_USERS = 'ORGANIZATION_USERS',
  ORGANIZATION_PROFILE = 'ORGANIZATION_PROFILE',
  ORGANIZATION_MEMBER = 'ORGANIZATION_MEMBER',

  CONFIGUARATION_ADMIN_STAFF = 'CONFIGUARATION_ADMIN_STAFF',
  CONFIGUARATION_ROLE_PERMISSION = 'CONFIGUARATION_ROLE_PERMISSION',

  ACTIVITY_LOG_ADMIN = 'ACTIVITY_LOG_ADMIN', // For Admin Site
  ACTIVITY_LOG = 'ACTIVITY_LOG', // For Client Site
  BULLETINS = 'BULLETINS',
  FEEDBACK_ADMIN = 'FEEDBACK_ADMIN',
  FEEDBACK = 'FEEDBACK',
  SYSTEM_CONFIG = 'SYSTEM_CONFIG',

  WORK_ORDER_ADMIN = 'WORK_ORDER_ADMIN',
  WORK_ORDER = 'WORK_ORDER',
  WORK_PERMIT_ADMIN = 'WORK_PERMIT_ADMIN',
  WORK_PERMIT = 'WORK_PERMIT',
  SCHEDULE_ADMIN = 'SCHEDULE_ADMIN',
  SCHEDULE = 'SCHEDULE',
  PERSONNEL_ADMIN = 'PERSONNEL_ADMIN',
  PERSONNEL = 'PERSONNEL',
  CAMPAIGN_PLAN_ADMIN = 'CAMPAIGN_PLAN_ADMIN',
  CAMPAIGN_PLAN = 'CAMPAIGN_PLAN',
}

export enum MODULE_NAME {
  AUTH = 'Authentication',
  MY_ACCOUNT = 'My Account',
  REGISTER_REQUEST = 'Register request',
  ORGANIZATION_MANAGEMENT = 'Organization Management',
  MEMBER_MANAGEMENT = 'Member Management',
  ADMIN_STAFF_MANAGEMENT = 'Admin staff Management',
  ROLE_PERMISSION = 'Role & Permission',
  BULLETINS_MANAGEMENT = 'Bulletins Management',
  FEEDBACK = 'Feedback Management',
}

export enum MODULE_NAME_FOR_CLIENT {
  AUTH = 'Authentication',
  MY_ACCOUNT = 'My Account',
  ORGANIZATION_MANAGEMENT = 'Organization Management',
  MEMBER_MANAGEMENT = 'Member Management',
  FEEDBACK = 'Feedback Management',
}
