export enum SortEnum {
  ASC = 'ASC',
  DESC = 'DESC',
}

export enum SortAdminStaffEnum {
  ADDED_DATE_ASC = 'ADDED_DATE_ASC',
  ADDED_DATE_DESC = 'ADDED_DATE_DESC',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
}

export enum SortPlanEnum {
  ADDED_DATE_ASC = 'ADDED_DATE_ASC',
  ADDED_DATE_DESC = 'ADDED_DATE_DESC',
}

export enum SortEnumCommon {
  ADDED_DATE_ASC = 'ADDED_DATE_ASC',
  ADDED_DATE_DESC = 'ADDED_DATE_DESC',
  NAME_ASC = 'NAME_ASC',
  NAME_DESC = 'NAME_DESC',
}

export enum AgeEnum {
  ZERO_TO_FIFTEEN = 'ZERO_TO_FIFTEEN',
  SIXTEEN_TO_TWENTY_FOUR = 'SIXTEEN_TO_TWENTY_FOUR',
  TWENTY_FIVE_TO_THIRTY_SIX = 'TWENTY_FIVE_TO_THIRTY_SIX',
  THIRTY_SEVEN_TO_FIFTY_FIVE = 'THIRTY_SEVEN_TO_FIFTY_FIVE',
  FIFTY_SIX_TO_SIXTY_FIVE = 'FIFTY_SIX_TO_SIXTY_FIVE',
  OVER_SIXTY_FIVE = 'OVER_SIXTY_FIVE',
}
