version: '3.8'

services:
  app:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${ENV}
    environment:
      NODE_ENV: ${ENV}
    deploy:
      replicas: 3  # Bạn có thể điều chỉnh số replicas (bản sao của dịch vụ) tùy ý
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    configs:
      - source: ${CONFIG_NAME}-${ENV}  # Chỉ định config từ Docker Swarm
        target: /app/.env  # Gắn config vào container tại /app/.env
    networks:
      - app-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

configs:
  ${CONFIG_NAME}-${ENV}:
    external: true  # Sử dụng config đã tạo bên ngoài

networks:
  app-net:
    external: true  # Mạng external đã được tạo từ trước
