name: CI/CD for NestJS Application

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Cập nhật lên phiên bản mới nhất

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Cập nhật lên phiên bản mới nhất
        with:
          node-version: '18'

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Run Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: lint # Job build sẽ chỉ chạy nếu job lint thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Cập nhật lên phiên bản mới nhất

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Cập nhật lên phiên bản mới nhất
        with:
          node-version: '18'

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build the application
        run: yarn build

      - name: Build Docker image
        run: docker build -t social-ai-backend .

  deploy:
    runs-on: ubuntu-latest
    needs: build # Job deploy chỉ chạy nếu job build thành công

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Cập nhật lên phiên bản mới nhất

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Cập nhật lên phiên bản mới nhất

      - name: Cache Docker layers
        uses: actions/cache@v3 # Cập nhật lên phiên bản mới nhất
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t social-ai-backend .

      - name: Save SSH key
        run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Check SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "echo 'SSH connected!'"

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /path/to/your/project
            docker-compose down
            docker-compose up -d --build
